//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  tarifs: Tarifs;
  tarifsConnection: TarifsConnection;
  abonnements: Abonnements;
  abonnementsConnection: AbonnementsConnection;
  ateliers: Ateliers;
  ateliersConnection: AteliersConnection;
  retraites: Retraites;
  retraitesConnection: RetraitesConnection;
  philosophie: Philosophie;
  philosophieConnection: PhilosophieConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  collaborations: Collaborations;
  collaborationsConnection: CollaborationsConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryTarifsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTarifsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TarifsFilter>;
};


export type QueryAbonnementsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAbonnementsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AbonnementsFilter>;
};


export type QueryAteliersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAteliersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AteliersFilter>;
};


export type QueryRetraitesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRetraitesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RetraitesFilter>;
};


export type QueryPhilosophieArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPhilosophieConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophieFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryCollaborationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCollaborationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CollaborationsFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  tarifs?: InputMaybe<TarifsFilter>;
  abonnements?: InputMaybe<AbonnementsFilter>;
  ateliers?: InputMaybe<AteliersFilter>;
  retraites?: InputMaybe<RetraitesFilter>;
  philosophie?: InputMaybe<PhilosophieFilter>;
  contact?: InputMaybe<ContactFilter>;
  collaborations?: InputMaybe<CollaborationsFilter>;
  settings?: InputMaybe<SettingsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Tarifs | Abonnements | Ateliers | Retraites | Philosophie | Contact | Collaborations | Settings | Folder;

export type HomeHero = {
  __typename?: 'HomeHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
  badgeNumber?: Maybe<Scalars['String']['output']>;
  badgeLabel?: Maybe<Scalars['String']['output']>;
};

export type HomeServicesCards = {
  __typename?: 'HomeServicesCards';
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type HomeServices = {
  __typename?: 'HomeServices';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<HomeServicesCards>>>;
};

export type HomePhilosophy = {
  __typename?: 'HomePhilosophy';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type HomeCta = {
  __typename?: 'HomeCta';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  services?: Maybe<HomeServices>;
  philosophy?: Maybe<HomePhilosophy>;
  cta?: Maybe<HomeCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
  badgeNumber?: InputMaybe<StringFilter>;
  badgeLabel?: InputMaybe<StringFilter>;
};

export type HomeServicesCardsFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type HomeServicesFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cards?: InputMaybe<HomeServicesCardsFilter>;
};

export type HomePhilosophyFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type HomeCtaFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  services?: InputMaybe<HomeServicesFilter>;
  philosophy?: InputMaybe<HomePhilosophyFilter>;
  cta?: InputMaybe<HomeCtaFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type TarifsRows = {
  __typename?: 'TarifsRows';
  duree?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  typeDetail?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type TarifsSoins = {
  __typename?: 'TarifsSoins';
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type Tarifs = Node & Document & {
  __typename?: 'Tarifs';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  notice?: Maybe<Scalars['String']['output']>;
  rows?: Maybe<Array<Maybe<TarifsRows>>>;
  soins?: Maybe<Array<Maybe<TarifsSoins>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TarifsRowsFilter = {
  duree?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  typeDetail?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type TarifsSoinsFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type TarifsFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  notice?: InputMaybe<StringFilter>;
  rows?: InputMaybe<TarifsRowsFilter>;
  soins?: InputMaybe<TarifsSoinsFilter>;
};

export type TarifsConnectionEdges = {
  __typename?: 'TarifsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tarifs>;
};

export type TarifsConnection = Connection & {
  __typename?: 'TarifsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TarifsConnectionEdges>>>;
};

export type AbonnementsPlans = {
  __typename?: 'AbonnementsPlans';
  name?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  popular?: Maybe<Scalars['Boolean']['output']>;
  feats?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Abonnements = Node & Document & {
  __typename?: 'Abonnements';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  sectionTitle?: Maybe<Scalars['String']['output']>;
  sectionSubtitle?: Maybe<Scalars['String']['output']>;
  plans?: Maybe<Array<Maybe<AbonnementsPlans>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AbonnementsPlansFilter = {
  name?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  popular?: InputMaybe<BooleanFilter>;
  feats?: InputMaybe<StringFilter>;
};

export type AbonnementsFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  sectionTitle?: InputMaybe<StringFilter>;
  sectionSubtitle?: InputMaybe<StringFilter>;
  plans?: InputMaybe<AbonnementsPlansFilter>;
};

export type AbonnementsConnectionEdges = {
  __typename?: 'AbonnementsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Abonnements>;
};

export type AbonnementsConnection = Connection & {
  __typename?: 'AbonnementsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AbonnementsConnectionEdges>>>;
};

export type AteliersItems = {
  __typename?: 'AteliersItems';
  title?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  priceUnit?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
};

export type AteliersPromo = {
  __typename?: 'AteliersPromo';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  priceBefore?: Maybe<Scalars['String']['output']>;
  priceAfter?: Maybe<Scalars['String']['output']>;
};

export type Ateliers = Node & Document & {
  __typename?: 'Ateliers';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  introEyebrow?: Maybe<Scalars['String']['output']>;
  introTitle?: Maybe<Scalars['String']['output']>;
  introText?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<AteliersItems>>>;
  promo?: Maybe<AteliersPromo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AteliersItemsFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  priceUnit?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
};

export type AteliersPromoFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  priceBefore?: InputMaybe<StringFilter>;
  priceAfter?: InputMaybe<StringFilter>;
};

export type AteliersFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  introEyebrow?: InputMaybe<StringFilter>;
  introTitle?: InputMaybe<StringFilter>;
  introText?: InputMaybe<StringFilter>;
  items?: InputMaybe<AteliersItemsFilter>;
  promo?: InputMaybe<AteliersPromoFilter>;
};

export type AteliersConnectionEdges = {
  __typename?: 'AteliersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Ateliers>;
};

export type AteliersConnection = Connection & {
  __typename?: 'AteliersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AteliersConnectionEdges>>>;
};

export type RetraitesRetreats = {
  __typename?: 'RetraitesRetreats';
  tag?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  activities?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type Retraites = Node & Document & {
  __typename?: 'Retraites';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  introEyebrow?: Maybe<Scalars['String']['output']>;
  introTitle?: Maybe<Scalars['String']['output']>;
  introText?: Maybe<Scalars['String']['output']>;
  retreats?: Maybe<Array<Maybe<RetraitesRetreats>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RetraitesRetreatsFilter = {
  tag?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  activities?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type RetraitesFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  introEyebrow?: InputMaybe<StringFilter>;
  introTitle?: InputMaybe<StringFilter>;
  introText?: InputMaybe<StringFilter>;
  retreats?: InputMaybe<RetraitesRetreatsFilter>;
};

export type RetraitesConnectionEdges = {
  __typename?: 'RetraitesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Retraites>;
};

export type RetraitesConnection = Connection & {
  __typename?: 'RetraitesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RetraitesConnectionEdges>>>;
};

export type PhilosophieCerts = {
  __typename?: 'PhilosophieCerts';
  text?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
};

export type Philosophie = Node & Document & {
  __typename?: 'Philosophie';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  quote?: Maybe<Scalars['String']['output']>;
  quoteAuthor?: Maybe<Scalars['String']['output']>;
  quoteRole?: Maybe<Scalars['String']['output']>;
  certs?: Maybe<Array<Maybe<PhilosophieCerts>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PhilosophieCertsFilter = {
  text?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
};

export type PhilosophieFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
  quoteAuthor?: InputMaybe<StringFilter>;
  quoteRole?: InputMaybe<StringFilter>;
  certs?: InputMaybe<PhilosophieCertsFilter>;
};

export type PhilosophieConnectionEdges = {
  __typename?: 'PhilosophieConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Philosophie>;
};

export type PhilosophieConnection = Connection & {
  __typename?: 'PhilosophieConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PhilosophieConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  notice?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  hoursWeek?: Maybe<Scalars['String']['output']>;
  hoursSunday?: Maybe<Scalars['String']['output']>;
  hoursSundayNote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  notice?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  hoursWeek?: InputMaybe<StringFilter>;
  hoursSunday?: InputMaybe<StringFilter>;
  hoursSundayNote?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type CollaborationsCollabs = {
  __typename?: 'CollaborationsCollabs';
  initials?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type Collaborations = Node & Document & {
  __typename?: 'Collaborations';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  introTitle?: Maybe<Scalars['String']['output']>;
  introText?: Maybe<Scalars['String']['output']>;
  collabs?: Maybe<Array<Maybe<CollaborationsCollabs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CollaborationsCollabsFilter = {
  initials?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type CollaborationsFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  introTitle?: InputMaybe<StringFilter>;
  introText?: InputMaybe<StringFilter>;
  collabs?: InputMaybe<CollaborationsCollabsFilter>;
};

export type CollaborationsConnectionEdges = {
  __typename?: 'CollaborationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Collaborations>;
};

export type CollaborationsConnection = Connection & {
  __typename?: 'CollaborationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CollaborationsConnectionEdges>>>;
};

export type SettingsFooter = {
  __typename?: 'SettingsFooter';
  description?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  siteName?: Maybe<Scalars['String']['output']>;
  siteTagline?: Maybe<Scalars['String']['output']>;
  planityUrl?: Maybe<Scalars['String']['output']>;
  instagramUrl?: Maybe<Scalars['String']['output']>;
  facebookUrl?: Maybe<Scalars['String']['output']>;
  formspreeId?: Maybe<Scalars['String']['output']>;
  siret?: Maybe<Scalars['String']['output']>;
  footer?: Maybe<SettingsFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SettingsFooterFilter = {
  description?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  siteTagline?: InputMaybe<StringFilter>;
  planityUrl?: InputMaybe<StringFilter>;
  instagramUrl?: InputMaybe<StringFilter>;
  facebookUrl?: InputMaybe<StringFilter>;
  formspreeId?: InputMaybe<StringFilter>;
  siret?: InputMaybe<StringFilter>;
  footer?: InputMaybe<SettingsFooterFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateTarifs: Tarifs;
  createTarifs: Tarifs;
  updateAbonnements: Abonnements;
  createAbonnements: Abonnements;
  updateAteliers: Ateliers;
  createAteliers: Ateliers;
  updateRetraites: Retraites;
  createRetraites: Retraites;
  updatePhilosophie: Philosophie;
  createPhilosophie: Philosophie;
  updateContact: Contact;
  createContact: Contact;
  updateCollaborations: Collaborations;
  createCollaborations: Collaborations;
  updateSettings: Settings;
  createSettings: Settings;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateTarifsArgs = {
  relativePath: Scalars['String']['input'];
  params: TarifsMutation;
};


export type MutationCreateTarifsArgs = {
  relativePath: Scalars['String']['input'];
  params: TarifsMutation;
};


export type MutationUpdateAbonnementsArgs = {
  relativePath: Scalars['String']['input'];
  params: AbonnementsMutation;
};


export type MutationCreateAbonnementsArgs = {
  relativePath: Scalars['String']['input'];
  params: AbonnementsMutation;
};


export type MutationUpdateAteliersArgs = {
  relativePath: Scalars['String']['input'];
  params: AteliersMutation;
};


export type MutationCreateAteliersArgs = {
  relativePath: Scalars['String']['input'];
  params: AteliersMutation;
};


export type MutationUpdateRetraitesArgs = {
  relativePath: Scalars['String']['input'];
  params: RetraitesMutation;
};


export type MutationCreateRetraitesArgs = {
  relativePath: Scalars['String']['input'];
  params: RetraitesMutation;
};


export type MutationUpdatePhilosophieArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophieMutation;
};


export type MutationCreatePhilosophieArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophieMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateCollaborationsArgs = {
  relativePath: Scalars['String']['input'];
  params: CollaborationsMutation;
};


export type MutationCreateCollaborationsArgs = {
  relativePath: Scalars['String']['input'];
  params: CollaborationsMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  tarifs?: InputMaybe<TarifsMutation>;
  abonnements?: InputMaybe<AbonnementsMutation>;
  ateliers?: InputMaybe<AteliersMutation>;
  retraites?: InputMaybe<RetraitesMutation>;
  philosophie?: InputMaybe<PhilosophieMutation>;
  contact?: InputMaybe<ContactMutation>;
  collaborations?: InputMaybe<CollaborationsMutation>;
  settings?: InputMaybe<SettingsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  tarifs?: InputMaybe<TarifsMutation>;
  abonnements?: InputMaybe<AbonnementsMutation>;
  ateliers?: InputMaybe<AteliersMutation>;
  retraites?: InputMaybe<RetraitesMutation>;
  philosophie?: InputMaybe<PhilosophieMutation>;
  contact?: InputMaybe<ContactMutation>;
  collaborations?: InputMaybe<CollaborationsMutation>;
  settings?: InputMaybe<SettingsMutation>;
};

export type HomeHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
  badgeNumber?: InputMaybe<Scalars['String']['input']>;
  badgeLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeServicesCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type HomeServicesMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<HomeServicesCardsMutation>>>;
};

export type HomePhilosophyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type HomeCtaMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  services?: InputMaybe<HomeServicesMutation>;
  philosophy?: InputMaybe<HomePhilosophyMutation>;
  cta?: InputMaybe<HomeCtaMutation>;
};

export type TarifsRowsMutation = {
  duree?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  typeDetail?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type TarifsSoinsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type TarifsMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  notice?: InputMaybe<Scalars['String']['input']>;
  rows?: InputMaybe<Array<InputMaybe<TarifsRowsMutation>>>;
  soins?: InputMaybe<Array<InputMaybe<TarifsSoinsMutation>>>;
};

export type AbonnementsPlansMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  popular?: InputMaybe<Scalars['Boolean']['input']>;
  feats?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AbonnementsMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  sectionSubtitle?: InputMaybe<Scalars['String']['input']>;
  plans?: InputMaybe<Array<InputMaybe<AbonnementsPlansMutation>>>;
};

export type AteliersItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  priceUnit?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
};

export type AteliersPromoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  priceBefore?: InputMaybe<Scalars['String']['input']>;
  priceAfter?: InputMaybe<Scalars['String']['input']>;
};

export type AteliersMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  introEyebrow?: InputMaybe<Scalars['String']['input']>;
  introTitle?: InputMaybe<Scalars['String']['input']>;
  introText?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<AteliersItemsMutation>>>;
  promo?: InputMaybe<AteliersPromoMutation>;
};

export type RetraitesRetreatsMutation = {
  tag?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  activities?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type RetraitesMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  introEyebrow?: InputMaybe<Scalars['String']['input']>;
  introTitle?: InputMaybe<Scalars['String']['input']>;
  introText?: InputMaybe<Scalars['String']['input']>;
  retreats?: InputMaybe<Array<InputMaybe<RetraitesRetreatsMutation>>>;
};

export type PhilosophieCertsMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
};

export type PhilosophieMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  quote?: InputMaybe<Scalars['String']['input']>;
  quoteAuthor?: InputMaybe<Scalars['String']['input']>;
  quoteRole?: InputMaybe<Scalars['String']['input']>;
  certs?: InputMaybe<Array<InputMaybe<PhilosophieCertsMutation>>>;
};

export type ContactMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  notice?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  hoursWeek?: InputMaybe<Scalars['String']['input']>;
  hoursSunday?: InputMaybe<Scalars['String']['input']>;
  hoursSundayNote?: InputMaybe<Scalars['String']['input']>;
};

export type CollaborationsCollabsMutation = {
  initials?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type CollaborationsMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  introTitle?: InputMaybe<Scalars['String']['input']>;
  introText?: InputMaybe<Scalars['String']['input']>;
  collabs?: InputMaybe<Array<InputMaybe<CollaborationsCollabsMutation>>>;
};

export type SettingsFooterMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  siteTagline?: InputMaybe<Scalars['String']['input']>;
  planityUrl?: InputMaybe<Scalars['String']['input']>;
  instagramUrl?: InputMaybe<Scalars['String']['input']>;
  facebookUrl?: InputMaybe<Scalars['String']['input']>;
  formspreeId?: InputMaybe<Scalars['String']['input']>;
  siret?: InputMaybe<Scalars['String']['input']>;
  footer?: InputMaybe<SettingsFooterMutation>;
};

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', eyebrow?: string | null, title?: string | null, subtitle?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, badgeNumber?: string | null, badgeLabel?: string | null } | null, services?: { __typename: 'HomeServices', eyebrow?: string | null, title?: string | null, subtitle?: string | null, cards?: Array<{ __typename: 'HomeServicesCards', title?: string | null, desc?: string | null, price?: string | null, cta?: string | null } | null> | null } | null, philosophy?: { __typename: 'HomePhilosophy', title?: string | null, text?: string | null, cta?: string | null } | null, cta?: { __typename: 'HomeCta', eyebrow?: string | null, title?: string | null, text?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null } | null };

export type TarifsPartsFragment = { __typename: 'Tarifs', pageTitle?: string | null, pageSubtitle?: string | null, notice?: string | null, rows?: Array<{ __typename: 'TarifsRows', duree?: string | null, type?: string | null, typeDetail?: string | null, prix?: string | null, description?: string | null } | null> | null, soins?: Array<{ __typename: 'TarifsSoins', title?: string | null, desc?: string | null, cta?: string | null, ctaLink?: string | null } | null> | null };

export type AbonnementsPartsFragment = { __typename: 'Abonnements', pageTitle?: string | null, pageSubtitle?: string | null, sectionTitle?: string | null, sectionSubtitle?: string | null, plans?: Array<{ __typename: 'AbonnementsPlans', name?: string | null, price?: string | null, period?: string | null, desc?: string | null, popular?: boolean | null, feats?: Array<string | null> | null } | null> | null };

export type AteliersPartsFragment = { __typename: 'Ateliers', pageTitle?: string | null, pageSubtitle?: string | null, introEyebrow?: string | null, introTitle?: string | null, introText?: string | null, items?: Array<{ __typename: 'AteliersItems', title?: string | null, price?: string | null, priceUnit?: string | null, desc?: string | null, date?: string | null } | null> | null, promo?: { __typename: 'AteliersPromo', title?: string | null, text?: string | null, priceBefore?: string | null, priceAfter?: string | null } | null };

export type RetraitesPartsFragment = { __typename: 'Retraites', pageTitle?: string | null, pageSubtitle?: string | null, introEyebrow?: string | null, introTitle?: string | null, introText?: string | null, retreats?: Array<{ __typename: 'RetraitesRetreats', tag?: string | null, title?: string | null, date?: string | null, location?: string | null, activities?: Array<string | null> | null, cta?: string | null } | null> | null };

export type PhilosophiePartsFragment = { __typename: 'Philosophie', pageTitle?: string | null, pageSubtitle?: string | null, eyebrow?: string | null, title?: string | null, paragraphs?: Array<string | null> | null, quote?: string | null, quoteAuthor?: string | null, quoteRole?: string | null, certs?: Array<{ __typename: 'PhilosophieCerts', text?: string | null, sub?: string | null } | null> | null };

export type ContactPartsFragment = { __typename: 'Contact', pageTitle?: string | null, pageSubtitle?: string | null, notice?: string | null, address?: string | null, phone?: string | null, email?: string | null, hoursWeek?: string | null, hoursSunday?: string | null, hoursSundayNote?: string | null };

export type CollaborationsPartsFragment = { __typename: 'Collaborations', pageTitle?: string | null, pageSubtitle?: string | null, introTitle?: string | null, introText?: string | null, collabs?: Array<{ __typename: 'CollaborationsCollabs', initials?: string | null, name?: string | null, role?: string | null, desc?: string | null } | null> | null };

export type SettingsPartsFragment = { __typename: 'Settings', siteName?: string | null, siteTagline?: string | null, planityUrl?: string | null, instagramUrl?: string | null, facebookUrl?: string | null, formspreeId?: string | null, siret?: string | null, footer?: { __typename: 'SettingsFooter', description?: string | null, copyright?: string | null } | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', eyebrow?: string | null, title?: string | null, subtitle?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, badgeNumber?: string | null, badgeLabel?: string | null } | null, services?: { __typename: 'HomeServices', eyebrow?: string | null, title?: string | null, subtitle?: string | null, cards?: Array<{ __typename: 'HomeServicesCards', title?: string | null, desc?: string | null, price?: string | null, cta?: string | null } | null> | null } | null, philosophy?: { __typename: 'HomePhilosophy', title?: string | null, text?: string | null, cta?: string | null } | null, cta?: { __typename: 'HomeCta', eyebrow?: string | null, title?: string | null, text?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', eyebrow?: string | null, title?: string | null, subtitle?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, badgeNumber?: string | null, badgeLabel?: string | null } | null, services?: { __typename: 'HomeServices', eyebrow?: string | null, title?: string | null, subtitle?: string | null, cards?: Array<{ __typename: 'HomeServicesCards', title?: string | null, desc?: string | null, price?: string | null, cta?: string | null } | null> | null } | null, philosophy?: { __typename: 'HomePhilosophy', title?: string | null, text?: string | null, cta?: string | null } | null, cta?: { __typename: 'HomeCta', eyebrow?: string | null, title?: string | null, text?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null } | null } | null } | null> | null } };

export type TarifsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TarifsQuery = { __typename?: 'Query', tarifs: { __typename: 'Tarifs', id: string, pageTitle?: string | null, pageSubtitle?: string | null, notice?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rows?: Array<{ __typename: 'TarifsRows', duree?: string | null, type?: string | null, typeDetail?: string | null, prix?: string | null, description?: string | null } | null> | null, soins?: Array<{ __typename: 'TarifsSoins', title?: string | null, desc?: string | null, cta?: string | null, ctaLink?: string | null } | null> | null } };

export type TarifsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TarifsFilter>;
}>;


export type TarifsConnectionQuery = { __typename?: 'Query', tarifsConnection: { __typename?: 'TarifsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TarifsConnectionEdges', cursor: string, node?: { __typename: 'Tarifs', id: string, pageTitle?: string | null, pageSubtitle?: string | null, notice?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rows?: Array<{ __typename: 'TarifsRows', duree?: string | null, type?: string | null, typeDetail?: string | null, prix?: string | null, description?: string | null } | null> | null, soins?: Array<{ __typename: 'TarifsSoins', title?: string | null, desc?: string | null, cta?: string | null, ctaLink?: string | null } | null> | null } | null } | null> | null } };

export type AbonnementsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AbonnementsQuery = { __typename?: 'Query', abonnements: { __typename: 'Abonnements', id: string, pageTitle?: string | null, pageSubtitle?: string | null, sectionTitle?: string | null, sectionSubtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, plans?: Array<{ __typename: 'AbonnementsPlans', name?: string | null, price?: string | null, period?: string | null, desc?: string | null, popular?: boolean | null, feats?: Array<string | null> | null } | null> | null } };

export type AbonnementsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AbonnementsFilter>;
}>;


export type AbonnementsConnectionQuery = { __typename?: 'Query', abonnementsConnection: { __typename?: 'AbonnementsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AbonnementsConnectionEdges', cursor: string, node?: { __typename: 'Abonnements', id: string, pageTitle?: string | null, pageSubtitle?: string | null, sectionTitle?: string | null, sectionSubtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, plans?: Array<{ __typename: 'AbonnementsPlans', name?: string | null, price?: string | null, period?: string | null, desc?: string | null, popular?: boolean | null, feats?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type AteliersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AteliersQuery = { __typename?: 'Query', ateliers: { __typename: 'Ateliers', id: string, pageTitle?: string | null, pageSubtitle?: string | null, introEyebrow?: string | null, introTitle?: string | null, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'AteliersItems', title?: string | null, price?: string | null, priceUnit?: string | null, desc?: string | null, date?: string | null } | null> | null, promo?: { __typename: 'AteliersPromo', title?: string | null, text?: string | null, priceBefore?: string | null, priceAfter?: string | null } | null } };

export type AteliersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AteliersFilter>;
}>;


export type AteliersConnectionQuery = { __typename?: 'Query', ateliersConnection: { __typename?: 'AteliersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AteliersConnectionEdges', cursor: string, node?: { __typename: 'Ateliers', id: string, pageTitle?: string | null, pageSubtitle?: string | null, introEyebrow?: string | null, introTitle?: string | null, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'AteliersItems', title?: string | null, price?: string | null, priceUnit?: string | null, desc?: string | null, date?: string | null } | null> | null, promo?: { __typename: 'AteliersPromo', title?: string | null, text?: string | null, priceBefore?: string | null, priceAfter?: string | null } | null } | null } | null> | null } };

export type RetraitesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RetraitesQuery = { __typename?: 'Query', retraites: { __typename: 'Retraites', id: string, pageTitle?: string | null, pageSubtitle?: string | null, introEyebrow?: string | null, introTitle?: string | null, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, retreats?: Array<{ __typename: 'RetraitesRetreats', tag?: string | null, title?: string | null, date?: string | null, location?: string | null, activities?: Array<string | null> | null, cta?: string | null } | null> | null } };

export type RetraitesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RetraitesFilter>;
}>;


export type RetraitesConnectionQuery = { __typename?: 'Query', retraitesConnection: { __typename?: 'RetraitesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RetraitesConnectionEdges', cursor: string, node?: { __typename: 'Retraites', id: string, pageTitle?: string | null, pageSubtitle?: string | null, introEyebrow?: string | null, introTitle?: string | null, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, retreats?: Array<{ __typename: 'RetraitesRetreats', tag?: string | null, title?: string | null, date?: string | null, location?: string | null, activities?: Array<string | null> | null, cta?: string | null } | null> | null } | null } | null> | null } };

export type PhilosophieQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PhilosophieQuery = { __typename?: 'Query', philosophie: { __typename: 'Philosophie', id: string, pageTitle?: string | null, pageSubtitle?: string | null, eyebrow?: string | null, title?: string | null, paragraphs?: Array<string | null> | null, quote?: string | null, quoteAuthor?: string | null, quoteRole?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, certs?: Array<{ __typename: 'PhilosophieCerts', text?: string | null, sub?: string | null } | null> | null } };

export type PhilosophieConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophieFilter>;
}>;


export type PhilosophieConnectionQuery = { __typename?: 'Query', philosophieConnection: { __typename?: 'PhilosophieConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PhilosophieConnectionEdges', cursor: string, node?: { __typename: 'Philosophie', id: string, pageTitle?: string | null, pageSubtitle?: string | null, eyebrow?: string | null, title?: string | null, paragraphs?: Array<string | null> | null, quote?: string | null, quoteAuthor?: string | null, quoteRole?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, certs?: Array<{ __typename: 'PhilosophieCerts', text?: string | null, sub?: string | null } | null> | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, pageTitle?: string | null, pageSubtitle?: string | null, notice?: string | null, address?: string | null, phone?: string | null, email?: string | null, hoursWeek?: string | null, hoursSunday?: string | null, hoursSundayNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, pageTitle?: string | null, pageSubtitle?: string | null, notice?: string | null, address?: string | null, phone?: string | null, email?: string | null, hoursWeek?: string | null, hoursSunday?: string | null, hoursSundayNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CollaborationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CollaborationsQuery = { __typename?: 'Query', collaborations: { __typename: 'Collaborations', id: string, pageTitle?: string | null, pageSubtitle?: string | null, introTitle?: string | null, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, collabs?: Array<{ __typename: 'CollaborationsCollabs', initials?: string | null, name?: string | null, role?: string | null, desc?: string | null } | null> | null } };

export type CollaborationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CollaborationsFilter>;
}>;


export type CollaborationsConnectionQuery = { __typename?: 'Query', collaborationsConnection: { __typename?: 'CollaborationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CollaborationsConnectionEdges', cursor: string, node?: { __typename: 'Collaborations', id: string, pageTitle?: string | null, pageSubtitle?: string | null, introTitle?: string | null, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, collabs?: Array<{ __typename: 'CollaborationsCollabs', initials?: string | null, name?: string | null, role?: string | null, desc?: string | null } | null> | null } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, siteName?: string | null, siteTagline?: string | null, planityUrl?: string | null, instagramUrl?: string | null, facebookUrl?: string | null, formspreeId?: string | null, siret?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, footer?: { __typename: 'SettingsFooter', description?: string | null, copyright?: string | null } | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, siteName?: string | null, siteTagline?: string | null, planityUrl?: string | null, instagramUrl?: string | null, facebookUrl?: string | null, formspreeId?: string | null, siret?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, footer?: { __typename: 'SettingsFooter', description?: string | null, copyright?: string | null } | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    eyebrow
    title
    subtitle
    ctaPrimary
    ctaSecondary
    badgeNumber
    badgeLabel
  }
  services {
    __typename
    eyebrow
    title
    subtitle
    cards {
      __typename
      title
      desc
      price
      cta
    }
  }
  philosophy {
    __typename
    title
    text
    cta
  }
  cta {
    __typename
    eyebrow
    title
    text
    ctaPrimary
    ctaSecondary
  }
}
    `;
export const TarifsPartsFragmentDoc = gql`
    fragment TarifsParts on Tarifs {
  __typename
  pageTitle
  pageSubtitle
  notice
  rows {
    __typename
    duree
    type
    typeDetail
    prix
    description
  }
  soins {
    __typename
    title
    desc
    cta
    ctaLink
  }
}
    `;
export const AbonnementsPartsFragmentDoc = gql`
    fragment AbonnementsParts on Abonnements {
  __typename
  pageTitle
  pageSubtitle
  sectionTitle
  sectionSubtitle
  plans {
    __typename
    name
    price
    period
    desc
    popular
    feats
  }
}
    `;
export const AteliersPartsFragmentDoc = gql`
    fragment AteliersParts on Ateliers {
  __typename
  pageTitle
  pageSubtitle
  introEyebrow
  introTitle
  introText
  items {
    __typename
    title
    price
    priceUnit
    desc
    date
  }
  promo {
    __typename
    title
    text
    priceBefore
    priceAfter
  }
}
    `;
export const RetraitesPartsFragmentDoc = gql`
    fragment RetraitesParts on Retraites {
  __typename
  pageTitle
  pageSubtitle
  introEyebrow
  introTitle
  introText
  retreats {
    __typename
    tag
    title
    date
    location
    activities
    cta
  }
}
    `;
export const PhilosophiePartsFragmentDoc = gql`
    fragment PhilosophieParts on Philosophie {
  __typename
  pageTitle
  pageSubtitle
  eyebrow
  title
  paragraphs
  quote
  quoteAuthor
  quoteRole
  certs {
    __typename
    text
    sub
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  pageTitle
  pageSubtitle
  notice
  address
  phone
  email
  hoursWeek
  hoursSunday
  hoursSundayNote
}
    `;
export const CollaborationsPartsFragmentDoc = gql`
    fragment CollaborationsParts on Collaborations {
  __typename
  pageTitle
  pageSubtitle
  introTitle
  introText
  collabs {
    __typename
    initials
    name
    role
    desc
  }
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  planityUrl
  instagramUrl
  facebookUrl
  formspreeId
  siret
  footer {
    __typename
    description
    copyright
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const TarifsDocument = gql`
    query tarifs($relativePath: String!) {
  tarifs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TarifsParts
  }
}
    ${TarifsPartsFragmentDoc}`;
export const TarifsConnectionDocument = gql`
    query tarifsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TarifsFilter) {
  tarifsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TarifsParts
      }
    }
  }
}
    ${TarifsPartsFragmentDoc}`;
export const AbonnementsDocument = gql`
    query abonnements($relativePath: String!) {
  abonnements(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AbonnementsParts
  }
}
    ${AbonnementsPartsFragmentDoc}`;
export const AbonnementsConnectionDocument = gql`
    query abonnementsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AbonnementsFilter) {
  abonnementsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AbonnementsParts
      }
    }
  }
}
    ${AbonnementsPartsFragmentDoc}`;
export const AteliersDocument = gql`
    query ateliers($relativePath: String!) {
  ateliers(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AteliersParts
  }
}
    ${AteliersPartsFragmentDoc}`;
export const AteliersConnectionDocument = gql`
    query ateliersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AteliersFilter) {
  ateliersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AteliersParts
      }
    }
  }
}
    ${AteliersPartsFragmentDoc}`;
export const RetraitesDocument = gql`
    query retraites($relativePath: String!) {
  retraites(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RetraitesParts
  }
}
    ${RetraitesPartsFragmentDoc}`;
export const RetraitesConnectionDocument = gql`
    query retraitesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RetraitesFilter) {
  retraitesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RetraitesParts
      }
    }
  }
}
    ${RetraitesPartsFragmentDoc}`;
export const PhilosophieDocument = gql`
    query philosophie($relativePath: String!) {
  philosophie(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PhilosophieParts
  }
}
    ${PhilosophiePartsFragmentDoc}`;
export const PhilosophieConnectionDocument = gql`
    query philosophieConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PhilosophieFilter) {
  philosophieConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PhilosophieParts
      }
    }
  }
}
    ${PhilosophiePartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const CollaborationsDocument = gql`
    query collaborations($relativePath: String!) {
  collaborations(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CollaborationsParts
  }
}
    ${CollaborationsPartsFragmentDoc}`;
export const CollaborationsConnectionDocument = gql`
    query collaborationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CollaborationsFilter) {
  collaborationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CollaborationsParts
      }
    }
  }
}
    ${CollaborationsPartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    tarifs(variables: TarifsQueryVariables, options?: C): Promise<{data: TarifsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TarifsQueryVariables, query: string}> {
        return requester<{data: TarifsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TarifsQueryVariables, query: string}, TarifsQueryVariables>(TarifsDocument, variables, options);
      },
    tarifsConnection(variables?: TarifsConnectionQueryVariables, options?: C): Promise<{data: TarifsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TarifsConnectionQueryVariables, query: string}> {
        return requester<{data: TarifsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TarifsConnectionQueryVariables, query: string}, TarifsConnectionQueryVariables>(TarifsConnectionDocument, variables, options);
      },
    abonnements(variables: AbonnementsQueryVariables, options?: C): Promise<{data: AbonnementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AbonnementsQueryVariables, query: string}> {
        return requester<{data: AbonnementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AbonnementsQueryVariables, query: string}, AbonnementsQueryVariables>(AbonnementsDocument, variables, options);
      },
    abonnementsConnection(variables?: AbonnementsConnectionQueryVariables, options?: C): Promise<{data: AbonnementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AbonnementsConnectionQueryVariables, query: string}> {
        return requester<{data: AbonnementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AbonnementsConnectionQueryVariables, query: string}, AbonnementsConnectionQueryVariables>(AbonnementsConnectionDocument, variables, options);
      },
    ateliers(variables: AteliersQueryVariables, options?: C): Promise<{data: AteliersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AteliersQueryVariables, query: string}> {
        return requester<{data: AteliersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AteliersQueryVariables, query: string}, AteliersQueryVariables>(AteliersDocument, variables, options);
      },
    ateliersConnection(variables?: AteliersConnectionQueryVariables, options?: C): Promise<{data: AteliersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AteliersConnectionQueryVariables, query: string}> {
        return requester<{data: AteliersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AteliersConnectionQueryVariables, query: string}, AteliersConnectionQueryVariables>(AteliersConnectionDocument, variables, options);
      },
    retraites(variables: RetraitesQueryVariables, options?: C): Promise<{data: RetraitesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RetraitesQueryVariables, query: string}> {
        return requester<{data: RetraitesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RetraitesQueryVariables, query: string}, RetraitesQueryVariables>(RetraitesDocument, variables, options);
      },
    retraitesConnection(variables?: RetraitesConnectionQueryVariables, options?: C): Promise<{data: RetraitesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RetraitesConnectionQueryVariables, query: string}> {
        return requester<{data: RetraitesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RetraitesConnectionQueryVariables, query: string}, RetraitesConnectionQueryVariables>(RetraitesConnectionDocument, variables, options);
      },
    philosophie(variables: PhilosophieQueryVariables, options?: C): Promise<{data: PhilosophieQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophieQueryVariables, query: string}> {
        return requester<{data: PhilosophieQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophieQueryVariables, query: string}, PhilosophieQueryVariables>(PhilosophieDocument, variables, options);
      },
    philosophieConnection(variables?: PhilosophieConnectionQueryVariables, options?: C): Promise<{data: PhilosophieConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophieConnectionQueryVariables, query: string}> {
        return requester<{data: PhilosophieConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophieConnectionQueryVariables, query: string}, PhilosophieConnectionQueryVariables>(PhilosophieConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    collaborations(variables: CollaborationsQueryVariables, options?: C): Promise<{data: CollaborationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CollaborationsQueryVariables, query: string}> {
        return requester<{data: CollaborationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CollaborationsQueryVariables, query: string}, CollaborationsQueryVariables>(CollaborationsDocument, variables, options);
      },
    collaborationsConnection(variables?: CollaborationsConnectionQueryVariables, options?: C): Promise<{data: CollaborationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CollaborationsConnectionQueryVariables, query: string}> {
        return requester<{data: CollaborationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CollaborationsConnectionQueryVariables, query: string}, CollaborationsConnectionQueryVariables>(CollaborationsConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/628ca68d-64b1-480b-9332-c239e0444bfc/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  